#! /bin/bash -x

export ARCH=xen
make image-xen
exit 0

# -- Old, but what the tmakefile does after kern-xen is there
cp xen.gz boot
cp kern-xen boot
echo "(fd0)	`pwd`/floppy.xen" > boot/boot/grub/device.map
genext2fs -b 1440 -d boot/ ./floppy.xen 
echo -e 'root (fd0)\ninstall /boot/grub/stage1 d (fd0) /boot/grub/stage2\nquit\n' | /usr/sbin/grub --batch --device-map=`pwd`/boot/boot/grub/device.map --no-floppy --boot-drive='(fd0)'
