#! /bin/bash
qemu -s -fda floppy.386 -m 32 -net user -net nic,model=rtl8139 -k en-us ${DELIRIUM_ARGS} $@ &
echo Hit [ENTER] to break in with gdb
read
TEXT=`ps ax | grep floppy.386 | grep -v grep`
if [ -z "${TEXT}" ]; then
 exit
fi
gdb -q ./kern-i386 :1234 
killall -HUP qemu
