#! /bin/bash -x
# use with:
# slattach -d -v -p slip /tmp/socat0
# ifconfig sl0 192.168.11.1 pointopoint 192.168.11.2 up
# ./qemu-delirium -serial tcp:0:5555

#socat -x PTY,link=/tmp/socat0,raw,clocal,echo=0 TCP-L:5555,reuseaddr,fork
#socat PTY,link=/tmp/socat0,raw,clocal,echo=0 TCP-L:5555,reuseaddr,fork
#socat PTY,link=/tmp/socat0,raw,clocal,echo=0 PTY,link=/tmp/socat1,raw,clocal,echo=0
socat PTY,link=/tmp/socat.tun,raw,clocal,echo=0,user=davidb TUN:192.168.11.1/24,up,iff-no-pi
